export const ADD_NEW_POST_REQUEST = "ADD_NEW_POST_REQUEST";
export const ADD_NEW_POST_SUCCESSFUL = "ADD_NEW_POST_SUCCESSFUL";
export const ADD_NEW_POST_FAILED = "ADD_NEW_POST_FAILED";
export const REMOVE_POST = "REMOVE_POST";
export const OPEN_POST = "OPEN_POST";
export const CLOSE_POST = "CLOSE_POST";
export const GET_ALL_POST_SUCCESSFUL = "GET_ALL_POST_SUCCESSFUL";
